### PR TITLE
Adapt to DeviceAccess 02.06 API

### PR DESCRIPTION
**Pull request by patrislav1**

### CODE REVIEW

**Comment by zenker** [comment]
I wonder if that is all that needs to be done. @mhier should know that...

**Comment by killenb** [comment]
We are not 100 % through with all the changes for DeviceAccess 02.06. But I am not aware of any subtle changes we introduced. Once it complies again, you should be good. We try to make it fail hard if we break something so you notice early.

**Comment by killenb** [comment]
BTW: Version DeviceAccess 02.06 and ApplicationCore 02.05 will probably be relased this week

**Comment by zenker** [comment]
Lets wait until the version is released.

**Pull request merged**
