### PR TITLE
Update to 64-bit interface; implement barIndexValid()

### PR DESCRIPTION
**Pull request by patrislav1**
Needs recent DeviceAccess ([a1378c3](https://github.com/ChimeraTK/DeviceAccess/commit/a1378c30010438fc612bef3d710f8afecb621225) or newer)

### CODE REVIEW

**Comment by zenker** [comment]
Can you update the required DeviceAccess version (and increase the minor version number) in the cmake file - I think the change is motivated by changes in DeviceAccess...

**Comment by zenker** [comment]
If I get it right the bar should be 3 or 4 right?
If yes this should be stated in the Readme.md. So far the bar index can be arbitrary.

**Comment by patrislav1** [comment]
> If I get it right the bar should be 3 or 4 right?
> If yes this should be stated in the Readme.md. So far the bar index can be arbitrary.

`barIndexValid()` is a new DeviceAccess API, but the limitation to 3 or 4 [has been there before](https://github.com/ChimeraTK/DeviceAccess-ModbusBackend/blob/1a99e5e0c4bb88b0a70fe4fb7ce747d6af3072c9/src/ModbusBackend.cc#L151).

**Comment by zenker** [comment]
I see so the Readme was not updated before. I just updated it.

**Pull request merged**
