### PR TITLE
fix recovery after TCP connection loss (cf. redmine #9821)

### PR DESCRIPTION
**Pull request by mhier**

### CODE REVIEW

**Comment by zenker** [comment]
I thought the backend should not react to calling open() if the connection is already open and simply do nothing. With your implementation every time open() is called it will create a new connection - without closing the old one!

**Comment by mhier** [comment]
fixed :-)

**Comment by zenker** [comment]
For me the tests are not running through. 
They get stock in somewhere in test_B_9_1, when calling https://github.com/ChimeraTK/DeviceAccess-ModbusBackend/blob/956451d40a29799a473a92013bf30191610471f8/tests/testModbus.C#L96

The other thread blocks here:
https://github.com/ChimeraTK/DeviceAccess-ModbusBackend/blob/956451d40a29799a473a92013bf30191610471f8/tests/testModbus.C#L137

I tested with debug flags. The commit I'm going to push is just cosmetics and does not change the situation.

**Comment by zenker** [comment]
I just realized that you dropped my changes with your previous commit - that is why I had a merge conflict. What was the reason for dropping my changes?

**Comment by mhier** [comment]
> I just realized that you dropped my changes with your previous commit - that is why I had a merge conflict. What was the reason for dropping my changes?

What changes did I drop? To me it looks like that all commits of the current master are in the branch.

**Comment by mhier** [comment]
Tests are running through for me. I am testing against heads of all other ChimeraTK libraries. Are you maybe using tags?

**Comment by zenker** [comment]
I was on the master branch but I was lacking a few commits. No tests are fine.

**Review by zenker — APPROVED** [review]

**Pull request merged**
